name: Integration
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  linux_build_and_test:
    runs-on: ubuntu-latest
    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Fetch tag git metadata
        run: git fetch --force --update-shallow --depth 1 origin +refs/tags/*:refs/tags/* || echo no tags
      - uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: 5.0.x
      - name: Build
        run: |
          dotnet build SharedMemory/SharedMemory.csproj --runtime linux-x64
          dotnet build SharedMemory.Tests/SharedMemory.Tests.csproj --runtime linux-x64
      - name: Test
        run: dotnet test SharedMemory.Tests/SharedMemory.Tests.csproj --no-build --runtime linux-x64
  macos_build_and_test:
    runs-on: macos-latest
    env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Fetch tag git metadata
        run: git fetch --force --update-shallow --depth 1 origin +refs/tags/*:refs/tags/* || echo no tags
      - uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: 5.0.x
      - name: Build
        run: |
          dotnet build SharedMemory/SharedMemory.csproj --runtime osx-x64
          dotnet build SharedMemory.Tests/SharedMemory.Tests.csproj --runtime osx-x64
      - name: Test
        run: dotnet test SharedMemory.Tests/SharedMemory.Tests.csproj --no-build --runtime osx-x64